// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xplqfwsjoxektoqslryq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbHFmd3Nqb3hla3RvcXNscnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTYzNTYsImV4cCI6MjA2ODYzMjM1Nn0.QchcGO7G1S-89HZLqlAyHqgLHtXFvSwRGegMFm6gb8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});